language: python

python:
  - 3.5

services:
  - docker

before_install:
  - pip install nose codecov

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=serapis --cover-inclusive

after_script:
  - codecov
